# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI Testing with Maven Surefire report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Generate Surefire report
      env:
        MEMORYMAZE_DB_URL: ${{ vars.MEMORYMAZE_DB_URL }}
        MEMORYMAZE_DB_USERNAME: ${{ vars.MEMORYMAZE_DB_USERNAME }}
        MEMORYMAZE_DB_PASSWORD: ${{ vars.MEMORYMAZE_DB_PASSWORD }}
      run: |
        echo "MEMORYMAZE_DB_URL=$MEMORYMAZE_DB_URL"
        echo "MEMORYMAZE_DB_USERNAME=$MEMORYMAZE_DB_USERNAME"
        echo "MEMORYMAZE_DB_PASSWORD=$MEMORYMAZE_DB_PASSWORD"
        mvn surefire-report:report
    - name: Upload Surefire report
      uses: actions/upload-artifact@v2
      with:
        name: surefire-report
        path: target/site/*